apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: "{{ appName }}{{ dashEnv }}"
  namespace: meldekort
  labels:
    team: meldekort
spec:
  image: "{{image}}"
  port: 8080
  secureLogs:
    enabled: true
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: "{{basePath}}/internal/isAlive"
    initialDelay: 10
  readiness:
    path: "{{basePath}}/internal/isReady"
    initialDelay: 10
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  prometheus:
    enabled: true
    path: "{{basePath}}/internal/metrics"
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 128Mi
  env:
    - name: BASE_PATH
      value: "{{ basePath }}"
    - name: DEKORATOR_MILJO
      value: "{{ dekoratorMiljo }}"
    - name: MELDEKORT_API_AUDIENCE
      value: "{{ meldekortApiAudience }}"
    - name: MELDEKORT_API_URL
      value: "{{ meldekortApiUrl }}"
    - name: MIN_SIDE_URL
      value: "{{ minSideUrl }}"
    - name: DP_URL
      value: "{{ dpUrl }}"
    - name: AAP_URL
      value: "{{ aapUrl }}"
    - name: AAP_API_AUDIENCE
      value: "{{ aapApiAudience }}"
    - name: TP_URL
      value: "{{ tpUrl }}"
    - name: TP_API_AUDIENCE
      value: "{{ tpApiAudience }}"
    - name: UMAMI_ID
      value: "{{umami_id}}"
    - name: SKAL_LOGGE
      value: "{{ skal_logge }}"
  accessPolicy:
    outbound:
      rules:
        - application: meldekort-api{{ dashEnv }}
        - application: nav-dekoratoren
          namespace: personbruker
        - application: meldekort-backend
          namespace: aap
        - application: tiltakspenger-meldekort-api
          namespace: tpts
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
      autoLogin: true
  tokenx:
    enabled: true
