export enum KortType {
  ORDINAER = 'ORDINAER',
  ERSTATNING = 'ERSTATNING',
  RETUR = 'RETUR',
  ELEKTRONISK = 'ELEKTRONISK',
  AAP = 'AAP',
  ORDINAER_MANUELL = 'ORDINAER_MANUELL',
  MASKINELT_OPPDATERT = 'MASKINELT_OPPDATERT',
  MANUELL_ARENA = 'MANUELL_ARENA',
  KORRIGERT_ELEKTRONISK = 'KORRIGERT_ELEKTRONISK'
}
